"""Reference clip format handling for ``ref_audio_base64``.

mlx_audio loads reference audio with ``miniaudio.get_file_info``, which picks
its parser from the FILE EXTENSION and never looks at the content. The server
used to store every inline clip as ``<sha256>.wav``, so an MP3 sent by the
client failed with "could not open/decode file" and every batch fell back to
serial and failed. The materialised file's extension must follow the real
format, and formats miniaudio cannot read must be refused up front.

The fixtures below are real 0.1 s sine clips (encoded once with ffmpeg and
embedded, so the tests need no ffmpeg): WAV / MP3 / FLAC / OGG are decodable
by miniaudio, M4A (``ftyp``) and raw ADTS AAC are not.
"""

import base64
import os
import stat
import time

import miniaudio
import pytest
from fastapi.testclient import TestClient

import wristtales_voice_server as wvs


@pytest.fixture(autouse=True)
def ref_dir(tmp_path, monkeypatch):
    """Point the temp-file directory at a per-test tmp dir."""
    directory = tmp_path / "ref"
    monkeypatch.setattr(wvs, "ref_audio_dir", lambda: directory)
    return directory


WAV_B64 = (
    "UklGRoYGAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAATElTVBoAAABJTkZPSVNGVA0AAABM"
    "YXZmNjMuMS4xMDIAAGRhdGFABgAAAABrBTIKxQ22D80PBQ6UCuQFgQAP+zP2f/Jk8CHwv/EM9ab5"
    "//52BGYJOw1+D+0Peg5QC9AGggEG/AP3D/Ok8AnwUfFX9L34/v19A5IIpAw3D/0P4A4ADLUHgQIB"
    "/dz3rfPz8AHw8/Cs89v3AP2AArQH/wvfDv0PNw+kDJMIfQP//b34V/RS8Qnwo/AP8wL3BfyBAc8G"
    "UAt5Du0Pfw87DWcJdwT//qb5DfW/8SHwY/B+8jL2DvuAAOMFlAoEDs0Ptw/FDTMKbAUAAJX6zvU7"
    "8krwM/D78Wz1HPp///EEzQmBDZwP3w9BDvQKWgYBAYr7mvbF8oLwE/CG8bD0MPl+/voD/QjxDFwP"
    "9w+vDqkLQwcCAoP8bvdc88nwA/Ag8QD0S/h//f8CJAhTDA0P/w8ND1QMJQgAA4D9TPgB9CHxA/DJ"
    "8FzzbfeD/AECQwepC64O9w9dD/EM/gj7A3/+Mfmw9IfxE/CB8MXymfaJ+wEBWgbzCkEO3w+dD4IN"
    "zgnyBID/Hfps9fzxM/BJ8DvyzfWU+gAAawUyCsUNtg/NDwUOlArkBYEAD/sz9n/yZPAh8L/xDPWm"
    "+f/+dgRmCTsNfg/tD3oOUAvQBoIBBvwD9w/zpPAJ8FHxV/S9+P79fQOSCKQMNw/9D+AOAAy1B4EC"
    "Af3c963z8/AB8PPwrPPb9wD9gAK0B/8L3w79DzcPpAyTCH0D//29+Ff0UvEJ8KPwD/MC9wX8gQHP"
    "BlALeQ7tD38POw1nCXcE//6m+Q31v/Eh8GPwfvIy9g77gADjBZQKBA7ND7cPxQ0zCmwFAACV+s71"
    "O/JK8DPw+/Fs9Rz6f//xBM0JgQ2cD98PQQ70CloGAQGK+5r2xfKC8BPwhvGw9DD5fv76A/0I8Qxc"
    "D/cPrw6pC0MHAgKD/G73XPPJ8APwIPEA9Ev4f/3/AiQIUwwND/8PDQ9UDCUIAAOA/Uz4AfQh8QPw"
    "yfBc8233g/wBAkMHqQuuDvcPXQ/xDP4I+wN//jH5sPSH8RPwgfDF8pn2ifsBAVoG8wpBDt8PnQ+C"
    "Dc4J8gSA/x36bPX88TPwSfA78s31lPoAAGsFMgrFDbYPzQ8FDpQK5AWBAA/7M/Z/8mTwIfC/8Qz1"
    "pvn//nYEZgk7DX4P7Q96DlAL0AaCAQb8A/cP86TwCfBR8Vf0vfj+/X0DkgikDDcP/Q/gDgAMtQeB"
    "AgH93Pet8/PwAfDz8Kzz2/cA/YACtAf/C98O/Q83D6QMkwh9A//9vfhX9FLxCfCj8A/zAvcF/IEB"
    "zwZQC3kO7Q9/DzsNZwl3BP/+pvkN9b/xIfBj8H7yMvYO+4AA4wWUCgQOzQ+3D8UNMwpsBQAAlfrO"
    "9TvySvAz8PvxbPUc+n//8QTNCYENnA/fD0EO9ApaBgEBivua9sXygvAT8IbxsPQw+X7++gP9CPEM"
    "XA/3D68OqQtDBwICg/xu91zzyfAD8CDxAPRL+H/9/wIkCFMMDQ//Dw0PVAwlCAADgP1M+AH0IfED"
    "8MnwXPNt94P8AQJDB6kLrg73D10P8Qz+CPsDf/4x+bD0h/ET8IHwxfKZ9on7AQFaBvMKQQ7fD50P"
    "gg3OCfIEgP8d+mz1/PEz8EnwO/LN9ZT6AABrBTIKxQ22D80PBQ6UCuQFgQAP+zP2f/Jk8CHwv/EM"
    "9ab5//52BGYJOw1+D+0Peg5QC9AGggEG/AP3D/Ok8AnwUfFX9L34/v19A5IIpAw3D/0P4A4ADLUH"
    "gQIB/dz3rfPz8AHw8/Cs89v3AP2AArQH/wvfDv0PNw+kDJMIfQP//b34V/RS8Qnwo/AP8wL3BfyB"
    "Ac8GUAt5Du0Pfw87DWcJdwT//qb5DfW/8SHwY/B+8jL2DvuAAOMFlAoEDs0Ptw/FDTMKbAUAAJX6"
    "zvU78krwM/D78Wz1HPp///EEzQmBDZwP3w9BDvQKWgYBAYr7mvbF8oLwE/CG8bD0MPl+/voD/Qjx"
    "DFwP9w+vDqkLQwcCAoP8bvdc88nwA/Ag8QD0S/h//f8CJAhTDA0P/w8ND1QMJQgAA4D9TPgB9CHx"
    "A/DJ8FzzbfeD/AECQwepC64O9w9dD/EM/gj7A3/+Mfmw9IfxE/CB8MXymfaJ+wEBWgbzCkEO3w+d"
    "D4INzgnyBID/Hfps9fzxM/BJ8DvyzfWU+g=="
)

MP3_B64 = (
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYzLjEuMTAyAAAAAAAAAAAAAAD/4zjAAAAAAAAAAAAA"
    "SW5mbwAAAA8AAAAEAAADGAB0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHSioqKioqKioqKioqKioqKi"
    "oqKioqKioqKi0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0f//////////////////////////////"
    "//8AAAAATGF2YzYzLjEuAAAAAAAAAAAAAAAAJAOgAAAAAAAAAxgUhadvAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/4yjEAB0wqohfTwAAC5tyUAB+/fv379/e"
    "9IDx48ePKUu/fv37/fhskEv4X4DuAtgQwwzjrejx48BCsHz+UOfKB/o9+sHDmIAffWDgYyAPvrAh"
    "zQD/KO78HwcBAEAQBAHwfB8HwICAIAgGAfB8H5QEAxv/8HwfAgIAgCDgOD4PvqBBTSLvAEDITf/X"
    "//+AACb/4yjEDh3B2mwBnJAABgiFQIYLCX7/H//zEY6MCBs9QqjQ5e0nQerSQQTPEIDO6UsDEMAj"
    "QPJA2kNmCyILCv/xSIfKGrRyhQQoIhouX//xcpNDnDnFEipFTIixFv//8xLpdMi8XkS6XUga//Eo"
    "SBoSnQ7///2LCDCiiijF6G4vZaS4rdmA/+vduLzK52CplID/4yjEGiMBiojxm5AAlNX9a266g5tN"
    "ICgwRhBgxSZsamRCetd2RIQoMgUBzCcAFgOCCxEPSHsP1X8uEUNC4XDQwLhAjcckmkyAmSf+yCDI"
    "IMggxMpLLqSy6ksu/BAocDBRyzolWdBX8MFJwpcVOgqVcGiv9FyPjQ0JRoaEqzolTEFNRTQuMFVV"
    "VVVVVVVVVVX/4yjEEQAAA0gBwAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU="
)

FLAC_B64 = (
    "ZkxhQwAAACIDIAMgAAFZAAFZAfQA8AAAAyAQwjlZxu/PiF5P0MPupVblBAAALAwAAABMYXZmNjMu"
    "MS4xMDIBAAAAFAAAAGVuY29kZXI9TGF2ZjYzLjEuMTAygQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAA//h0CAADH/dOAAAFawoyDcUPtg/NDgUKlOYt4qRuQcfXYJU+"
    "0GHNfmWAAXcoEQkCIByUiESFgYZCnvhQwk5ECJcKQwoByRLM4SYFJoVCIaEkJMIgWIEEnDAoGhIl"
    "NDJISSUKXJgRAwkoaUIJOBhMyXIhyFCFApC7lAiEgRAOSkQiQsDDIU98KGEnIgRLhSGFAOSJZnCT"
    "ApNCoRDQkhJhECxAgk4YFA0JEpoZJCSShS5MCIGElDShBJwMJmS5EOQoQoFIXcoEQkCIByUiESFg"
    "YZCnvhQwk5ECJcKQwoByRLM4SYFJoVCIaEkJMIgWIEEnDAoGhIlNDJISSUKXJgRAwkoaUIJOBhMy"
    "XIhyFCFApC7lAiEgRAOSkQiQsDDIU98KGEnIgRLhSGFAOSJZnCTApNCoRDQkhJhECxAgk4YFA0JE"
    "poZJCSShS5MCIGElDShBJwMJmS5EOd9/"
)

OGG_B64 = (
    "T2dnUwACAAAAAAAAAABXKBfUAAAAAO1sux0BHgF2b3JiaXMAAAAAAkAfAAAAAAAAAAAAAAAAAAC7"
    "AU9nZ1MAAAAAAAAAAAAAVygX1AEAAAAIRKNqDjv///////////////+7A3ZvcmJpcwwAAABMYXZm"
    "NjMuMS4xMDIBAAAAGwAAAGVuY29kZXI9TGF2YzYzLjEuMTAyIHZvcmJpcwEFdm9yYmlzHEJDVgIA"
    "EAAAhHSaWaoBIsxAhoHQkJUAAAIAAGCEIgwxIDRkJQAAEAAAIIaSg2hCa8435zholoOmUmxOBydS"
    "bZ7kpmJuzjnnnHOyOWeMc845pyhnFoNmQmvOOScxaJaCZkJrzjnnSWwetKZKa845Z5xzOhhnhHHO"
    "OadJax6kZmNtzjlnQWuao+ZSbM45J1JuntTmUm3OOeecc84555xzzjmnenE6B+eEc845J2pvruUm"
    "dHHOOeeTcbo3J4RzzjnnnHPOOeecc845JwgNWQkAAAEAEIRhYxh3CoL0ORqIUYSYhkx60D06TILG"
    "IKeQejQ6GimlDkJJZZyU0glCQ1YCAIAAABBCSCGFFFJIIYUUUkghhRhiiCGGnHLKKaigkkoqqiij"
    "zDLLLLPMMssssw4766zDDkMMMcTQSiux1FRbjTXWmnvOueYgrZXWWmutlFJKKaWUgtCQlQAACAAA"
    "gZBBBhlkFFJIIYUYYsopp5yCCiogNGQlAAAGAMAhZ6CBBhpooIEGGmigccYZiCCCCCKopJJMOgop"
    "tdhqzDHXXoMOOveee++5+ByEUkoppZRSSimllFJKKSUIDVkJAIAAAAAIIYQQUkghhRRSijHGHHMO"
    "OgklBEJDVgIAYAAADDHEGGSQQUghhRhiiinHHHMMOgghlFJSaKGFXGqIJZZWWomlpZhqi7HWWHPt"
    "Mdbee++9995777333nvOgdCQlQBABAAAgwwiiCCCjDEGIQSEhqwEAEAAABBiiDHGIIQQUoghp5yC"
    "TDLppKOQAqEhKwEAJwAAhBFHJHEEEmeggQgqqSCjzEIssbXWWmuttdZaa6211lprrbXWWmuttdZa"
    "a6211lprLRAashIAiAAAYJBBBhlEEEEEGWSA0JCVAAAIAAAjjEAEGaUUY4455hh00EEnHYUWWiA0"
    "ZCUA4AQAQCChiDLMMAQRVVRRRhVVFFJHKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimlVEoppQRC"
    "Q1YCAGQAAJCilFIpLUWCIqUYpBhLRhVzUFqKqHIMUs2pUs4g5iSWiDGElJNUMuYUQgxC6hx1TCkG"
    "LZUYQsYYpNhyS6FzDggNWSEAhGYAOBwHkCwLkCwLAAAAAAAAACRNAzTPAyzNAwAAAAAAAABJ0wDL"
    "0wDN8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAkDQN0DwP0DwPAAAAAAAAADTPAzxPBDxRBAAAAAAAAADL8wBN9ABPFAEA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAkDQN0DwP0DwPAAAAAAAAACzPAzxRBDRPBAAAAAAAAADL8wBPFAFP9AAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAo4AAAKWAiFhqwIAOIEAByS"
    "BEmCJEHzAJJlQdOgaTBNgGRZ0DRoGkwTAAAAAAAAAAAAAEnToGnQNIgiQNI0aBo0DaIIAAAAAAAA"
    "AAAAgKRp0DRoGkQRIGkaNA2aBlEEAAAAAAAAAAAAwDNNiCJEEaYJ8EwToghRhGkCAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAIAAAkcAAAFTCgDhYasCADiBAAcjmJZAADgOI5lAQCA4ziWBQAAlmWJIgAA"
    "WJYmigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAgAACRwAAAVMKAOFhqwEAKIAAByKYlnAcSwLOI5lAUmyLIBlATQPoGkAUQQA"
    "AgAADRwAAAVs0JRYHKDQkJUAQBQAgEFxLEvTRJEkaZrmiSJJ0jTPE0Wa5nmeZ5rwPM8zTYiiKJom"
    "RFEUTROmaZqqCkxTVQUAABo4AAAK2KApsThAoSErAYCQAACHoliWpnme54miaaomSdI0zxNFUTRN"
    "01RVkqRpnieKomiapqmqLEvTPE8URdE0VVVVoWmeJ4qiaJqqqrrwPM8TRVE0TVV1XXie54miKJqm"
    "qrouRFEUTdM0VVNVXReIommapqqqqusC0RNF01RV13Vd4HmiaJqq6qquC0TTNFVVVV1XlgGmaZqq"
    "6rqyDFBVVXVd15VlgKqqquu6riwDVNV1XVeWZRmA67quLMuyAABABAcAQAEj6CSjyiJsNOHCA1Bo"
    "yIoAIAoAADCGKcWUMoxJCCmEhjEJIYWQSUmptJQqCKmUVEoFIZWSSskopZRaShWEVEoqpYKQSkml"
    "FAAAi+AAAItgIRQashIAyAMAIIxRijHGnJMIKcWYc85JhJRizDnnpFKMOeecc1JKxhxzzjkppXPO"
    "OeeclJI555xzTkrpnHPOOSellNI555yTUkoJoXPQSSmldM455wQAgBo4AAAK2CiyOcFIUKEhKwGA"
    "VAAAg+NYlqZ5niiapiVJmuZ5nieKpqlJkqZ5nueJomryPM8TRVE0TVXleZ4niqJomqrKdUXRNE1T"
    "VVWXLIuiaZqmqrouTNM0VdV1XRemaZqq6rquC9tWVVV1XVmGbauqqrquLAPXdV1ZtmUgy64ru7Ys"
    "AABewQEA1MCG1RFOisYCCw1ZCQBkAAAQxiCkEEJIGYSQQgghpRRCAgAACRwAAAVMKAOFhqwEAFIB"
    "AABjrLXWWmutNdBZa6211lorILPWWmuttdZaa6211lprrbXUWmuttdZaa6211lprrbXWWmuttdZa"
    "a6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaSymllFJKKaWUUkoppZRSSimllFIBQL8WDgD/"
    "EDasjnBSNBZYaMhKACAcAAAwRinGHINQSikVQow5Jx2V1mKsEGLMOQkptRZb8ZxzEEpIpbUYi+ec"
    "g1BKSrHVWFQKoZSUUost1qJS6KiklFJrNRZjTCqptdZiq7EYY1IKLbXWYozFCFtTai222mosxtia"
    "SgstxhhjMcIXGVuLqbZagzHCyBZLS7XWGowxRvfWYqmt5mKMD762FEuMNRcA4O7gAICoYOMMK0ln"
    "haPBhYasBABCAgAIhJRijDHGnHPOOakUY44555yDEEIolWKMMeecgxBCCCVjjDnnHIQQQgihlJIx"
    "5xyEEEIIIaSUOucchBBCCCGEUkrnnIMQQgghhFBK6SCEEEIIIYQSSikphRBCCCGEEEIqKaUQQgih"
    "lBBKSCWlFEIIIYRQSgkppZRCCKGUEEIoIaWUUkohhBBCKaWklFJKqYRSQgmhhFRKSimFEkIIpZSS"
    "UkoplVJCKKGEUkpJKaWUUgghhFJKAQCACA4AgAJG0ElGlUXYaMKFByAAAAAEACAIkRkiUbAADA5U"
    "AELCFABQWGCQAwANDg9pFxfQZYALurjrQAhBCEIQiwMoIAEHJ9zwxBuecIMTdIpKDQgAAAAAABkA"
    "fAAAJA9AREQ0cxAREhMUFRYXGBkaGxwAAIAAAgAAEAAAAAAACAAAAAAQT2dnUwAEQAMAAAAAAABX"
    "KBfUAgAAAIZUlY0E/9T/tl7mskBEihAI+hCiCR2UwEiozGWBiBQhEPQhRBM6KIGR0DlPr93LaPfa"
    "0e61I3vtfwCACADgnDFGk2VZVlVVBBwdHOxWB8PB7uhgt1rE0bTbHO0Wi10dLQ52m8UMKWREZhRZ"
    "jYZr18qMyIyQiEsYn0iChInGxMXHJ5Ig0UTjEsTGx8UlmjBBIrEJY+ISJkwkkfhEY+Li4xNJkDDx"
    "mERi4xPEJZpogsTEJoyLSzTRRBITn3iMubmJwdzcwlSr0WuNipmJ1Ktm5pZ6Cwtzc3MznYU2PiYu"
    "PmFMImF8JCY2PiZBNGEQE42NiYsmDOLC2Ji42ISRuDA2iInGR+LC+CAmGhuJi8YHMWE0EhOND+Lc"
    "bTrdnk2P6plO27PTo+2ZTttterQ906O6Taft2fSobjptt+lR3XSq23TanulU23TabjrVpmm76VQ3"
    "TbXpVFdTbTrVTUebprrpaNNUm051NaUfqqIfuqIfuqIe+qEq+qEq+qEr6qErqqIfqqIfqqIeuqIq"
    "uqIqdaiKR1VUURVVrKiKRVWi0Wg0Go1Go9FoNBqNRqPRaDQajUaj0Wg0Go1Go9FoNBqNRqPRaDQa"
    "jUaj0Wg0Go1Go9FoNBqNRqPRaDQajUaj0WgUXtZSoUeIEAj6FIoOSsEICZW1VOgRIgSCPoWig1Iw"
    "QkLPZE97e5Mbbb3JZ6OtN7nRzt60N57Jnvb2JnvR3t7kPwAAAMA5ewyWZbmqqggAu9WG3XCwGFa1"
    "qYPVtBgOhqNhsVodTQe1GjabYcdm2u2mReyGg8ViNR1MB9M0DEexi6FWR7WpVRwcxMSCgx0RK3aL"
    "qGnDYio2GTKIFGVEvYEGa1UjMmQQyUxnKQyqqaVGYFCkQWOUUmCpVVUzvbnW0kKJSzxOiSYSxiYS"
    "T1yikUjCOOITRMME8YpLNCZImMCxCWKdIGEQSRij+ARhNEEscfFBEB9HbIJoGBevSHxE8XGOxkUd"
    "Ex9E4jt69mjbHj11ejZNzx66Pdrq0TOdnk26nWp7dHV6punZ0e1UdbqabpNuR9tpq9NN023S7VTb"
    "aTXdpNt4ua8u/Vdenq/y5Xc86qt8+R2P+ipf9nHpv/JyX136rzz7KvRPefwq9T4e/1OfZep04PH0"
    "q2WqMnA6fT31WUmdDlxPP5epysDp9PUyqaROB66nn2XKHjidvl4mFe+0fj39LFP2wGH6LpOKd1q/"
    "npPSswcO0zc="
)

M4A_B64 = (
    "AAAAHGZ0eXBNNEEgAAACAE00QSBpc29taXNvMgAAAAhmcmVlAAAD421kYXTcAExhdmM2My4xLjEw"
    "MgACNGhSLJDkbYXLnjesv15LrepnlUsyZrJrtEf/yjiu0+fdF2rpNmuNNI4bE3KNr2Rx1pNMWz6q"
    "Y5LKdCsOS2mtPslXbFacdwPYvMejbTxXWejbzyr8mpgTKH7NkEhIpyMEUzAIiETr3rGhy6HNWQQ/"
    "+VAh5S0juLm3TVk09bOOvR23B8Lm53B7r7vOxcrc86tqsnGrY1GqivkpElEiZjXimZ0UplqLfJaZ"
    "jPCCU8+EVbxzaq1rorU2u4ozM6tvktRb5LTMa8UzGvPktRb5LRN+8VNjcUZmdxXyWot+8UzGvFMx"
    "rz5LUW+8UTfeK0t/l0t/lRfc96+59Tpb/KDf5UXG5TcssqL/L1P3PYdLfm0Xoy+jLLLLLL6Jn0dh"
    "l3uVHL/l2H0fkfo/m5fzew+jLLLLLLLLLLLLLLLLLjLLKqUzKjlRyymZTOKOVGxKZxR4o1SmZQPF"
    "HKjMygeIHKjYRgcoHijYRsSgeIG6NhGB4gZD6cfV8n99/h8Q/Ov98Cf57PzOEPun+I4n9HPkwQ/F"
    "98vSf6FfxlkPyS/luJ/UP7lkPsb8Tyf5eftCQ/PV+WUn+Dn8eZD5+/Pcn+Fj5QEPz2/iVJ/lZ/Ms"
    "Q+sv4Pif01+P5D8jP1iJ/nq/KYQ/Dx+Uon82/rCQ+4fxDJ/ng/C+Q/Md+a4n9m/xUkPnn8wCf4uv"
    "pWQ/PL+Skn+L/8xxD51/c8n9fvkaQ/Lf+AMn+b/84RD7p/kXJ/Ln6NkPwk/QQn+cb8fnARg0LbSW"
    "QigAAACIwiAN06l5ipvum4ObtW6Z6SvPtWwOwsy8R5m975zbHr2Z/FeHbS+F0J+e0X9p6G629t3p"
    "+m2P/Z6IqYFohl0GTh+HkRj+gJHDWp7FQSE2Z0EXQyA0EpsqUaxHE0SVLgBLmXQCXKduTrMI1pmC"
    "OJRkYKysVkgplcJEZPTMCF3zRIPu3kX23NH5LM/VPiuze06B99h/Pc23rieS49P8ZwGvYW850/7S"
    "8Y6o0teh8S0sV/WaKGsqieTxsE/SKyeNxsx+eZUkbapFSVayLaiKpq1k5YkKnalMUxINXdt81dWM"
    "YXzV1YxhZjXJTRguNslNGC4lJTNWOMSXzV1Yxgc1clKYLNbJSlazFJTRWuMSXzVjjEhzV1Uxgc1s"
    "lKVrMUlKGipJKiGijQWSKokoqsdBCpJKiG1TRUkVRJRVY6SKgyVENqmipJKihFVjpIqiSgQ2qaKk"
    "kqIaKrHSRVElFVjpoqSSohtU00SKokoqsdZK0EqIbVNFSVNElFVjpIrQSxDapoqSSooatY6SKoks"
    "VaqyVJcAAAMCbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAfQAAAAyAAAQAAAQAAAAAAAAAAAAAA"
    "AAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAgAAAi10cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAAyAAAAAAAAAAAAAA"
    "AAEBAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAkZWR0"
    "cwAAABxlbHN0AAAAAAAAAAEAAAMgAAAEAAABAAAAAAGlbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAA"
    "AAAfQAAAByBVxAAAAAAALWhkbHIAAAAAAAAAAHNvdW4AAAAAAAAAAAAAAABTb3VuZEhhbmRsZXIA"
    "AAABUG1pbmYAAAAQc21oZAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAA"
    "AAABAAABFHN0YmwAAABqc3RzZAAAAAAAAAABAAAAWm1wNGEAAAAAAAAAAQAAAAAAAAAAAAEAEAAA"
    "AAAfQAAAAAAANmVzZHMAAAAAA4CAgCUAAQAEgICAF0AVAAAAAAC7gAAAh0cFgICABRWIVuUABoCA"
    "gAECAAAAIHN0dHMAAAAAAAAAAgAAAAEAAAQAAAAAAQAAAyAAAAAcc3RzYwAAAAAAAAABAAAAAQAA"
    "AAIAAAABAAAAHHN0c3oAAAAAAAAAAAAAAAIAAAJBAAABmgAAABRzdGNvAAAAAAAAAAEAAAAsAAAA"
    "GnNncGQBAAAAcm9sbAAAAAIAAAAB//8AAAAcc2JncAAAAAByb2xsAAAAAQAAAAIAAAABAAAAYXVk"
    "dGEAAABZbWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAsaWxzdAAA"
    "ACSpdG9vAAAAHGRhdGEAAAABAAAAAExhdmY2My4xLjEwMg=="
)

AAC_B64 = (
    "//FsQEkf/NwATGF2YzYzLjEuMTAyAAI0aFIskORthcueN6y/Xkut6meVSzJmsmu0R//KOK7T590X"
    "auk2a400jhsTco2vZHHWk0xbPqpjksp0Kw5Laa0+yVdsVpx3A9i8x6NtPFdZ6NvPKvyamBMofs2Q"
    "SEinIwRTMAiIROvesaHLoc1ZBD/5UCHlLSO4ubdNWTT1s469HbcHwubncHuvu87Fytzzq2qycatj"
    "UaqK+SkSUSJmNeKZnRSmWot8lpmM8IJTz4RVvHNqrWuitTa7ijMzq2+S1FvktMxrxTMa8+S1Fvkt"
    "E37xU2NxRmZ3FfJai37xTMa8UzGvPktRb7xRN94rS3+XS3+VF9z3r7n1Olv8oN/lRcblNyyyov8v"
    "U/c9h0t+bRejL6MsssssvomfR2GXe5Ucv+XYfR+R+j+bl/N7D6MssssssssssssssssuMssqpTMq"
    "OVHLKZlM4o5UbEpnFHijVKZlA8UcqMzKB4gcqNhGBygeKNhGxKB4gbo2EYHiBkPpx9Xyf33+HxD8"
    "6/3wJ/ns/M4Q+6f4jif0c+TBD8X3y9J/oV/GWQ/JL+W4n9Q/uWQ+xvxPJ/l5+0JD89X5ZSf4Ofx5"
    "kPn789yf4WPlAQ/Pb+JUn+Vn8yxD6y/g+J/TX4/kPyM/WIn+er8phD8PH5Sifzb+sJD7h/EMn+eD"
    "8L5D8x35rif2b/FSQ+efzAJ/i6+lZD88v5KSf4v/zHEPnX9zyf1++RpD8t/4Ayf5v/zhEPun+Rcn"
    "8ufo2Q/CT9BCf5xvx+f/8WxAND/8ARg0LbSWQigAAACIwiAN06l5ipvum4ObtW6Z6SvPtWwOwsy8"
    "R5m975zbHr2Z/FeHbS+F0J+e0X9p6G629t3p+m2P/Z6IqYFohl0GTh+HkRj+gJHDWp7FQSE2Z0EX"
    "QyA0EpsqUaxHE0SVLgBLmXQCXKduTrMI1pmCOJRkYKysVkgplcJEZPTMCF3zRIPu3kX23NH5LM/V"
    "Piuze06B99h/Pc23rieS49P8ZwGvYW850/7S8Y6o0teh8S0sV/WaKGsqieTxsE/SKyeNxsx+eZUk"
    "bapFSVayLaiKpq1k5YkKnalMUxINXdt81dWMYXzV1YxhZjXJTRguNslNGC4lJTNWOMSXzV1Yxgc1"
    "clKYLNbJSlazFJTRWuMSXzVjjEhzV1Uxgc1slKVrMUlKGipJKiGijQWSKokoqsdBCpJKiG1TRUkV"
    "RJRVY6SKgyVENqmipJKihFVjpIqiSgQ2qaKkkqIaKrHSRVElFVjpoqSSohtU00SKokoqsdZK0EqI"
    "bVNFSVNElFVjpIrQSxDapoqSSooatY6SKoksVaqyVJc="
)


def _decode(b64: str) -> bytes:
    return base64.b64decode(b64)


# --- extension follows the real format -------------------------------------


@pytest.mark.parametrize(
    "b64, extension",
    [
        (WAV_B64, ".wav"),
        (MP3_B64, ".mp3"),
        (FLAC_B64, ".flac"),
        (OGG_B64, ".ogg"),
    ],
    ids=["wav", "mp3", "flac", "ogg"],
)
def test_extension_is_sniffed_and_file_is_decodable(b64, extension, ref_dir):
    path = wvs.materialize_reference_audio(b64)
    assert path.endswith(extension)
    assert os.path.dirname(path) == str(ref_dir)
    with open(path, "rb") as fh:
        assert fh.read() == _decode(b64)
    # The very call mlx_audio makes: it must accept the file we hand it.
    assert miniaudio.get_file_info(path).sample_rate > 0


def test_mp3_is_not_stored_as_wav(ref_dir):
    """Regression: an MP3 named .wav makes miniaudio raise DecodeError."""
    path = wvs.materialize_reference_audio(MP3_B64)
    assert not path.endswith(".wav")
    assert [p.name for p in ref_dir.iterdir()] == [os.path.basename(path)]


def test_bare_mpeg_frame_without_id3_is_mp3(ref_dir):
    """An MP3 with its ID3 tag stripped starts straight at a frame sync."""
    data = _decode(MP3_B64)
    assert data.startswith(b"ID3")
    # Skip the ID3v2 tag (10-byte header + synchsafe size).
    size = (data[6] << 21) | (data[7] << 14) | (data[8] << 7) | data[9]
    bare = data[10 + size :]
    assert bare[0] == 0xFF and bare[1] & 0xE0 == 0xE0
    path = wvs.materialize_reference_audio(base64.b64encode(bare).decode())
    assert path.endswith(".mp3")
    assert miniaudio.get_file_info(path).sample_rate > 0


def test_wav_is_reused_on_second_call(ref_dir):
    first = wvs.materialize_reference_audio(WAV_B64)
    assert first.endswith(".wav")
    mtime = os.stat(first).st_mtime_ns
    second = wvs.materialize_reference_audio(WAV_B64)
    assert second == first
    assert [p.name for p in ref_dir.iterdir()] == [os.path.basename(first)]
    assert os.stat(first).st_mtime_ns >= mtime


def test_mp3_is_reused_on_second_call(ref_dir):
    first = wvs.materialize_reference_audio(MP3_B64)
    second = wvs.materialize_reference_audio(MP3_B64)
    assert second == first
    assert len(list(ref_dir.iterdir())) == 1


def test_file_mode_stays_private_for_every_format(ref_dir):
    for b64 in (WAV_B64, MP3_B64, FLAC_B64, OGG_B64):
        path = wvs.materialize_reference_audio(b64)
        assert stat.S_IMODE(os.stat(path).st_mode) == 0o600
    assert not [p for p in ref_dir.iterdir() if p.name.startswith(".tmp-")]


# --- formats miniaudio cannot decode are a 400 -----------------------------


@pytest.mark.parametrize(
    "data",
    [
        _decode(M4A_B64),  # ISO-BMFF: size + "ftyp"
        _decode(AAC_B64),  # raw ADTS AAC: 0xFFF1 sync, but layer bits 00
        b"FORM\x00\x00\x00\x08AIFFCOMM",  # AIFF
        b"RIFF\x04\x00\x00\x00AVI LIST",  # RIFF, but not WAVE
        b"\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b",  # noise
        b"x",  # shorter than any header
    ],
    ids=["m4a", "adts-aac", "aiff", "riff-not-wave", "noise", "one-byte"],
)
def test_unsupported_format_is_400_and_nothing_is_written(data, ref_dir):
    with pytest.raises(wvs.ReferenceAudioError) as exc:
        wvs.materialize_reference_audio(base64.b64encode(data).decode())
    assert exc.value.status_code == 400
    for name in ("WAV", "MP3", "FLAC", "OGG"):
        assert name in exc.value.detail
    assert not ref_dir.exists() or not list(ref_dir.iterdir())


def test_unsupported_format_is_400_over_http_on_the_batch_route(monkeypatch):
    """The 400 reaches the client as JSON ``detail`` before any model work."""

    def fail(*_a, **_k):
        raise AssertionError("must not reach the inference broker")

    monkeypatch.setattr(wvs, "get_inference_broker", fail)
    monkeypatch.setattr(wvs, "_ensure_batch_adapter_registered", lambda: None)
    monkeypatch.setattr(wvs, "_install_model_aliases", lambda: None)
    resp = TestClient(wvs.app).post(
        "/v1/audio/speech/batch",
        json={
            "model": "bosonai/higgs-audio-v3-tts-4b",
            "inputs": ["Ahoj."],
            "ref_audio_base64": M4A_B64,
        },
    )
    assert resp.status_code == 400
    assert "WAV, MP3, FLAC or OGG" in resp.json()["detail"]


# --- cleanup is extension-agnostic -----------------------------------------


def test_startup_cleanup_covers_every_extension(ref_dir):
    ref_dir.mkdir()
    long_ago = time.time() - 25 * 3600
    stale = [ref_dir / f"old.{ext}" for ext in ("wav", "mp3", "flac", "ogg")]
    for p in stale:
        p.write_bytes(b"x")
        os.utime(p, (long_ago, long_ago))
    fresh = ref_dir / "fresh.mp3"
    fresh.write_bytes(b"x")

    assert wvs.cleanup_stale_ref_audio() == 4
    assert not any(p.exists() for p in stale)
    assert fresh.exists()
